In [38]:
import numpy as np
import pandas as pd
from scipy.spatial.distance import cosine
from scipy.stats.stats import pearsonr

In [39]:
data = pd.read_pickle('../clean-data/dataf.pickle')

In [57]:
data1 = data.fillna(0)
nmat = data1.as_matrix()

In [8]:
def cos(a, b):
    a = np.array(a)
    b = np.array(b)
    return 1 - cosine(a,b)

In [17]:
def euc(a, b):
    a = np.array(a)
    b = np.array(b)
    return 1.0/ (1 + np.linalg.norm(a-b))
    

In [24]:
def pr(a,b):
    a = np.array(a)
    b = np.array(b)   
    return pearsonr(a,b)[0]

In [35]:
idict  = dict(zip(range(97),data.columns))

In [36]:
udict = dict(zip(range(2174),data.index))

In [171]:
def sim(matrix, a, b, t = 'pr'):
    aval = matrix[a].nonzero()
    bval = matrix[b].nonzero()
    shared = np.intersect1d(aval, bval)
    print(shared)
    if len(shared) == 0:
        return 0
    a = np.take(matrix[a], shared)
    print(a)
    b = np.take(matrix[b], shared)
    print(b)
    if t =='euc':
        return euc(a,b)
    elif t == 'cos':
        return cos(a,b)
    else:
        return pr(a,b) 

In [154]:
def user_user(a,n):
    score_list={}
    for b in udict.keys():
        if(b!=a):#Compute Pearson Correlation Value for Every Other User in the List
            score_list[b]=sim(nmat, a, b)       
    sorteddict = sorted(score_list.values())
    return sorteddict[-n:]

In [165]:
for i in range(2174):
    print(i, sim(nmat,0,i))

0 1.0
1 0
2 0
3 0
4 0
5 0
6 0
7 0
8 0
9 0
10 0
11 nan
12 0
13 nan
14 0
15 0
16 0
17 nan
18 0
19 nan
20 0
21 0
22 0
23 0
24 0
25 0
26 0
27 0
28 0
29 0
30 0
31 nan
32 0
33 0
34 nan
35 nan
36 0
37 0
38 0
39 0
40 -1.0
41 0
42 0
43 0
44 0
45 nan
46 0
47 0
48 0
49 0
50 0
51 0
52 0
53 0
54 0
55 nan
56 0
57 0
58 0
59 0
60 0
61 0
62 0
63 0
64 nan
65 -1.0
66 0
67 0
68 nan
69 nan
70 0
71 0
72 0
73 0
74 0
75 0
76 nan
77 0
78 nan
79 nan
80 0
81 0
82 0
83 nan
84 0
85 0
86 0
87 0
88 0
89 nan
90 0
91 nan
92 0
93 0
94 0
95 nan
96 nan
97 0
98 nan
99 0
100 0
101 0
102 0
103 nan
104 0
105 0
106 0
107 0
108 0
109 nan
110 0
111 0
112 nan
113 0
114 0
115 0
116 0
117 0
118 0
119 0
120 0
121 0
122 0
123 0
124 0
125 0
126 0
127 -1.0
128 0
129 0
130 0
131 0
132 nan
133 0
134 0
135 0
136 0
137 0
138 0
139 0
140 0
141 nan
142 nan
143 0
144 0
145 0
146 0
147 0
148 0
149 0
150 0
151 0
152 0
153 0
154 0
155 nan
156 0
157 nan
158 0
159 0
160 0
161 0
162 nan
163 0
164 0
165 nan
166 0
167 0
168 0
169 0
170 nan
171 0
172

In [172]:
sim(nmat,0,11)

[48 50 52 79]
[ 9.  9.  9.  9.]
[ 9.  9.  9.  9.]


nan

In [169]:
cosin

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  10.,   0.,   0.,
         0.,   0.,   0.,   0.,   9.,   9.,   9.,   9.,   9.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   9.,   0.,   0.,
         0.,   0.,   9.,   0.,   0.,   7.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.])

In [170]:
nmat[11]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  9.,  0.,  9.,  0.,
        9.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  9.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.])

In [187]:
pearsonr([5, 5], [5, 5])

(nan, nan)